package org.stenio.docmanager.model;

import java.util.Date;

public class FileItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.size
     *
     * @mbggenerated
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.is_dir
     *
     * @mbggenerated
     */
    private Byte isDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.m_time
     *
     * @mbggenerated
     */
    private Date mTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.file_code
     *
     * @mbggenerated
     */
    private String fileCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.project_code
     *
     * @mbggenerated
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.item_code
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.research_stage
     *
     * @mbggenerated
     */
    private String researchStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.build_date
     *
     * @mbggenerated
     */
    private Date buildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_item.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.id
     *
     * @return the value of file_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.id
     *
     * @param id the value for file_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.uid
     *
     * @return the value of file_item.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.uid
     *
     * @param uid the value for file_item.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.dir
     *
     * @return the value of file_item.dir
     *
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.dir
     *
     * @param dir the value for file_item.dir
     *
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.name
     *
     * @return the value of file_item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.name
     *
     * @param name the value for file_item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.size
     *
     * @return the value of file_item.size
     *
     * @mbggenerated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.size
     *
     * @param size the value for file_item.size
     *
     * @mbggenerated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.is_dir
     *
     * @return the value of file_item.is_dir
     *
     * @mbggenerated
     */
    public Byte getIsDir() {
        return isDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.is_dir
     *
     * @param isDir the value for file_item.is_dir
     *
     * @mbggenerated
     */
    public void setIsDir(Byte isDir) {
        this.isDir = isDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.md5
     *
     * @return the value of file_item.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.md5
     *
     * @param md5 the value for file_item.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.c_time
     *
     * @return the value of file_item.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.c_time
     *
     * @param cTime the value for file_item.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.m_time
     *
     * @return the value of file_item.m_time
     *
     * @mbggenerated
     */
    public Date getmTime() {
        return mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.m_time
     *
     * @param mTime the value for file_item.m_time
     *
     * @mbggenerated
     */
    public void setmTime(Date mTime) {
        this.mTime = mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.file_code
     *
     * @return the value of file_item.file_code
     *
     * @mbggenerated
     */
    public String getFileCode() {
        return fileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.file_code
     *
     * @param fileCode the value for file_item.file_code
     *
     * @mbggenerated
     */
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode == null ? null : fileCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.project_code
     *
     * @return the value of file_item.project_code
     *
     * @mbggenerated
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.project_code
     *
     * @param projectCode the value for file_item.project_code
     *
     * @mbggenerated
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode == null ? null : projectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.item_code
     *
     * @return the value of file_item.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.item_code
     *
     * @param itemCode the value for file_item.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.project_name
     *
     * @return the value of file_item.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.project_name
     *
     * @param projectName the value for file_item.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.research_stage
     *
     * @return the value of file_item.research_stage
     *
     * @mbggenerated
     */
    public String getResearchStage() {
        return researchStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.research_stage
     *
     * @param researchStage the value for file_item.research_stage
     *
     * @mbggenerated
     */
    public void setResearchStage(String researchStage) {
        this.researchStage = researchStage == null ? null : researchStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.build_date
     *
     * @return the value of file_item.build_date
     *
     * @mbggenerated
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.build_date
     *
     * @param buildDate the value for file_item.build_date
     *
     * @mbggenerated
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.editor
     *
     * @return the value of file_item.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.editor
     *
     * @param editor the value for file_item.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_item.file_type
     *
     * @return the value of file_item.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_item.file_type
     *
     * @param fileType the value for file_item.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }
}