package org.stenio.docmanager.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.stenio.docmanager.model.FileItem;
import org.stenio.docmanager.model.FileItemCriteria;

public interface FileItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int countByExample(FileItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int deleteByExample(FileItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int insert(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int insertSelective(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    List<FileItem> selectByExample(FileItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    FileItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FileItem record, @Param("example") FileItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FileItem record, @Param("example") FileItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileItem record);
}